---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dev.
--- DateTime: 2019-03-21 15:47
---
package.path = package.path..";/Users/dev/Documents/lua/test/?.lua"

require("module")

print('ssss')


print(b)

b = 1

print(b)
print("----------------------------")
tab1 = { key1 = "aaa", key2 = "zzz", "asd", "yyy" }

for k, v in pairs(tab1) do

    print(k, "-", v)
end
print("----------------------------")
tab1.key1 = nil
for k, v in pairs(tab1) do

    print(k .. "-" .. v)
end
print("----------------------------")
print(type(nil) == nil)
print("----------------------------")

local tbl1 = {}
local tbl2 = { "aaa", "ddd", "vvv", "nnn" }
for k, v in pairs(tbl2) do
    print(k, v)
end
print("----------------------------")

a3 = {}

for i = 1, 10 do
    a3[i] = i
end

print(4, a3[4])
print("----------------------------")
function hallo(n)
    if n == 0 then
        return 1
    else
        return n * hallo(n - 1)
    end
end

print(hallo(3))
print("----------------------------")

function testfun(tab, fun)

    for k, v in pairs(tab) do

        print(fun(k, v))
    end
end
tab = { key1 = "aaa", key1 = "vvv", key3 = "ggg" }
testfun(tab, function(key, value)
    return key, value
end)

while (true)
do
    print("sssss")
    break
end
print("----------------------------")

b = 0
repeat

    b = b + 1
    print(b)
until b == 10
print("----------------------------")
if (0)
then
    print("0===true")

else print("false")
end
print("----------------------------")
function max(num1,num2)

    if(num1>num2)then
        result=num1
    else
        result=num2
    end
    return result
end

print("最大值：",max(5,1))
print("最大值：",max(2,9))
print("----------------------------")

s,e=string.find("sadad","ad")
w,t=string.len("ssaad"),string.len("adad")
print(s,e)
print(w,t)
print("----------------------------")
function maxmum(a)
    local mi=1;
    local m=a[mi]

    for i, v in ipairs(a) do

        if v>m then
            mi=i;
            m=v

        end
    end
    return m,mi
end

print(maxmum({5,3,11,23,6,1}))


print(module.constant)

module.func3()


function table_max(t)

    for i, v in ipairs(t) do

        print(i,v)
    end
end
print("----------------------------")
tab11={3,4}
tab12={4}

function combine(mytable,newtable)

    for i, v in ipairs(newtable) do

        table.insert(mytable,v)
    end
    return mytable

end

combine(tab11,tab12)
for i, v in ipairs(tab11) do

    print(i,v)
end

--file=io.open("test.lua","r")
--io.input(file)
--
--print(debug.getinfo(file))

print(collectgarbage("count"))
print(collectgarbage("collect"))
print(collectgarbage("count"))
print("----------------------------")
Student={id=0,name="",age=0,sex=""}

--function Student:new (id,name,age,sex)
--
--    Obj=id or {}
--
--    setmetatable(id,self)
--
--    self._index=self
--    self.name=name or "hih"
--    self.age=12 or 0
--    self.sex="女" or 0
--
--    return Obj
--
--end
--
--function Student:printName()
--
--    print(self.name)
--end
Teache={id=0,name="",age=0,sex=""}

s=Teache:new(1,"sad",13,"男")
print(s.name)