---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dev.
--- DateTime: 2019-03-21 17:21
---

module={}
module.constant="常量"
function module.func1()
    io.write("这个是共有函数")
end

local function func2()
    print("这个是私有函数")
end

function module.func3()
    func2()
end



return module